.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH x 1  "x " 
.SH NAME
x
.SH SYNOPSIS
\fBx\fR [\fB\-C\fR|\fB\-\-color\fR] [\fB\-P\fR|\fB\-\-profile\fR] [\fB\-v\fR|\fB\-\-version\fR] [\fB\-j\fR|\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-color\fR [default: auto]

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
icon
.IP \(bu 2
auto
.IP \(bu 2
never
.RE
.TP
\fB\-P\fR, \fB\-\-profile\fR \fI<FILE>\fR

.TP
\fB\-v\fR, \fB\-\-version\fR
Show version
.TP
\fB\-j\fR, \fB\-\-json\fR
Output results as JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
x\-accounts(1)
List accounts.
.TP
x\-authorize(1)
Authorize an application via OAuth.
.TP
x\-bookmark(1)
Bookmark posts.
.TP
x\-bookmarks(1)
Returns the most recent bookmarked posts.
.TP
x\-block(1)
Block users.
.TP
x\-blocks(1)
Returns a list of blocked users.
.TP
x\-direct_messages(1)
Returns the 20 most recent Direct Messages sent to you.
.TP
x\-direct_messages_sent(1)
Returns the 20 most recent Direct Messages you\*(Aqve sent.
.TP
x\-dm(1)
Sends that person a Direct Message.
.TP
x\-does_contain(1)
Find out whether a list contains a user.
.TP
x\-does_follow(1)
Find out whether one user follows another.
.TP
x\-favorite(1)
Marks posts as favorites.
.TP
x\-favorites(1)
Returns the 20 most recent posts you favorited.
.TP
x\-follow(1)
Follow users.
.TP
x\-followings(1)
Returns a list of the people you follow.
.TP
x\-followings_following(1)
Displays your friends who follow the specified user.
.TP
x\-followers(1)
Returns a list of the people who follow you.
.TP
x\-friends(1)
Returns the list of people who you follow and follow you back.
.TP
x\-groupies(1)
Returns the list of people who follow you but you don\*(Aqt follow back.
.TP
x\-intersection(1)
Displays the intersection of users followed by the specified users.
.TP
x\-leaders(1)
Returns the list of people who you follow but don\*(Aqt follow you back.
.TP
x\-lists(1)
Returns the lists created by a user.
.TP
x\-collections(1)
Returns the collections created by a user.
.TP
x\-matrix(1)
Unfortunately, no one can be told what the Matrix is. You have to see it for yourself.
.TP
x\-mentions(1)
Returns the 20 most recent posts mentioning you.
.TP
x\-mute(1)
Mute users.
.TP
x\-muted(1)
Returns a list of the people you have muted.
.TP
x\-open(1)
Opens that user\*(Aqs profile in a web browser.
.TP
x\-reach(1)
Shows the maximum number of people who may have seen the specified post in their timeline.
.TP
x\-reply(1)
Post a reply directed at another person.
.TP
x\-report_spam(1)
Report users for spam.
.TP
x\-retweet(1)
Repost posts to your followers.
.TP
x\-retweets(1)
Returns the 20 most recent reposts by a user.
.TP
x\-retweets_of_me(1)
Returns the 20 most recent posts of the authenticated user that have been reposted by others.
.TP
x\-ruler(1)
Prints a 280\-character ruler.
.TP
x\-status(1)
Retrieves detailed information about a post.
.TP
x\-timeline(1)
Returns the 20 most recent posts by a user.
.TP
x\-trends(1)
Returns the top 50 trending topics.
.TP
x\-my_location(1)
Retrieves place information based on your IP address.
.TP
x\-nearby_places(1)
Retrieves nearby places using an address or your IP geolocation.
.TP
x\-place(1)
Retrieves detailed information about a place.
.TP
x\-places(1)
Retrieves places with similar names near an address or your IP geolocation.
.TP
x\-trend_locations(1)
Returns the locations for which X has trending topic information.
.TP
x\-unfollow(1)
Unfollow users.
.TP
x\-unbookmark(1)
Remove bookmarked posts.
.TP
x\-update(1)
Post to your timeline.
.TP
x\-users(1)
Returns a list of users you specify.
.TP
x\-version(1)
Show version.
.TP
x\-whois(1)
Retrieves profile information for the user.
.TP
x\-whoami(1)
Retrieves profile information for the authenticated user.
.TP
x\-collection(1)
Manage collections.
.TP
x\-delete(1)
Delete posts, Direct Messages, etc.
.TP
x\-list(1)
Manage lists.
.TP
x\-search(1)
Search posts.
.TP
x\-set(1)
Change various account settings.
.TP
x\-stream(1)
Stream posts in real time.
